### ISSUE TITLE
apple data off my one

### ISSUE THREAD

**Issue by woolfg** [openpodcast/api#157]
![Image](https://github.com/openpodcast/api/assets/1328269/c4e942cd-0782-4c8d-abaf-445e71050417)

https://podcastsconnect.apple.com/podcasts/pcc/v1/analytics/showTrendsV2?showId=.......&start=2023-10-10&end=2023-12-08&mode=ROLLING_60&seriesMode=DAILY&metric=PLAYS&dimension=BY_EPISODES

all rows that have 0 plays have 1 play on apple. if there is no db row at all, it is a proper "0 plays" case and correct. so the the row is inserted but with 0 instead of 1. Higher values are stored correctly, it is just the 1 plays cases

**Comment by mre** [comment]
Could it be a connector bug?

**Comment by woolfg** [comment]
from the connector only days which are not 0 are received. although the playscount is always 0. should be a value between 1 and 3

```
"showPlayCountTrends": [
      {
        "podcastid": "123",
        "playscount": 0,
        "timebucket": 20231202,
        "followstate": "*",
        "totaltimelistened": 128,
        "uniquelistenerscount": 0,
        "uniqueengagedlistenerscount": 0
      },
      {
        "podcastid": "123",
        "playscount": 0,
        "timebucket": 20231203,
        "followstate": "*",
        "totaltimelistened": 133,
        "uniquelistenerscount": 0,
        "uniqueengagedlistenerscount": 0
      },
      {
        "podcastid": "123",
        "playscount": 0,
        "timebucket": 20231207,
        "followstate": "*",
        "totaltimelistened": 2034,
        "uniquelistenerscount": 0,
        "uniqueengagedlistenerscount": 0
      },
      {
        "podcastid": "123",
        "playscount": 0,
        "timebucket": 20231208,
        "followstate": "*",
        "totaltimelistened": 1408,
        "uniquelistenerscount": 0,
        "uniqueengagedlistenerscount": 0
      }
```

**Comment by woolfg** [comment]
if we fetch one week as usual `&start=2023-12-01&end=2023-12-09&mode=ROLLING_60&seriesMode=DAILY&metric=PLAYS&dimension=BY_EPISODES` it is not working. 

I tried to track it down. it works from 2023-11-19 to 2023-12-09 ... so at least 20 days or it is something else.

**Comment by woolfg** [comment]
a quick fix could be to the set the date range for apple to 60 days. as the number of requests is independent of the number of days for apple, it wouldn't increase the connector crawling time.
