### ISSUE TITLE
when selecting 3 months as a date range,  LTR charts are not shown

### ISSUE THREAD

**Issue by woolfg** [openpodcast/api#164]

**Comment by woolfg** [comment]
fixed in https://github.com/openpodcast/api/commit/61e5b5d1c659824d739f353a3920095bd2694af0

**Comment by mre** [comment]
What about the start date? Should we do the same in that case?

**Comment by mre** [comment]
(Reopening for clarification. Feel free to close after that. 😉)

**Comment by woolfg** [comment]
there is no start date ;) ... we just the newest in this query, there is no lower bound.

**Comment by mre** [comment]
Oh whoops, sorry.
