### ISSUE TITLE
Account 2 data is missing in Spotify Podcast Metadata

### ISSUE THREAD

**Issue by woolfg** [openpodcast/api#32]
![image](https://user-images.githubusercontent.com/1328269/204916857-92933494-9785-4874-86e8-9a7684a1f0c2.png)

**Comment by mre** [comment]
We resolved this, I guess.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/175809/215605183-4c26a717-f8bb-4f7b-9eb7-c9d0b9f4980e.png">
