### ISSUE TITLE
Add support for date parameter for `analytics` queries

### ISSUE THREAD

**Issue by mre** [openpodcast/api#61]
Example: http://localhost/analytics/v1/podcastGender?date=2023-02-12

**Comment by woolfg** [comment]
I would suggest to add start/end as params to be more flexible. the user can then decide if just one day is needed or a range should be fetched from the API

**Comment by mre** [comment]
tackling this next

**Comment by woolfg** [comment]
could we use markdown/yaml/frontmatter/json to define the SQL queries and metadata? would be the advantage that we do not have to invent our own format?

**Comment by mre** [comment]
I think we can. Let's introduce the date parameters manually first and then consider rewriting it to dbt. I have a feeling that it will simplify things a lot.

**Comment by mre** [comment]
We decided that we'll try to use SQL variables, which are a nice tradeoff between customizability and fully native SQL syntax.

**Comment by woolfg** [comment]
in progress openpodcast/api#67
